title: 林国锋个人博客
email: linguofeng@msn.com
description: java,android,linux,ubuntu,osx,cocos2d-x,c++,c,cpp,hhkb,lua,vim,raspberrypi
baseurl: ""
url: "https://linguofeng.com"
enforce_ssl: "linguofeng.com"
twitter_username: linguofeng
github_username:  linguofeng

# Build settings
markdown: kramdown
